config/routes.rb
Rails.application.routes.draw do

  get 'tools/index'

  resources :information

  root 'welcome#index'
  get 'welcome/index'

  resources :gets

  get 'posts/test'
  resources :posts

end

app/models/get.rb
class Get < ActiveRecord::Base
# gets数据库表中有三个字段，都是必须填写的
  validates :title, presence: true
  validates :url, presence: true
  validates :result, presence: true
end

app/controllers/gets_controller.rb
class GetsController < ApplicationController
# 在执行方法之前先
# 1. 查找到对应的get数据
  before_action :set_get, only: [:show, :edit, :update, :destroy]
# 2. 设置好cucumber自动化测试文件的路径
  before_action :set_featureFile, only: [:create, :edit, :update, :destroy]

  # GET /gets
  # GET /gets.json
# 对应于前台的"get用例列表"
  def index
    if params[:project].nil?
      @gets = Get.paginate :page => params[:page],
                           :per_page => 10
    else
      @gets = Get.where(project: "#{params[:project].to_i}").order("title").paginate :page => params[:page],
                                                                                     :per_page => 10
#      case params[:project].to_i
#        when 1 then
#          @gets = Get.where(project: "1")
#        when 2 then
#          @gets = Get.where(project: "2")
#        when 3 then
#          @gets = Get.where(project: "3")
#        when 4 then
#          @gets = Get.where(project: "4")
#        when 5 then
#          @gets = Get.where(project: "5")
#        when 6 then
#          @gets = Get.where(project: "6")
#        when 7 then
#          @gets = Get.where(project: "7")
#        when 8 then
#          @gets = Get.where(project: "8")
#      else
#        raise "invalid project"
#      end
    end
  end

  # GET /gets/1
  # GET /gets/1.json
  def show
  end

  # GET /gets/new
# 对应于前台的"新建Get用例"，创建用例页面，输入参数页面
  def new
    @get = Get.new
  end

  # GET /gets/1/edit
  def edit
  end

  # POST /gets
  # POST /gets.json
# 点击"新建Get用例页面"的创建按钮，后台执行的操作，保存测试用例，同时创建cucumber自动化测试用例
  def create
# 获取页面填写的get参数
    @get = Get.new(get_params)
    case @get[:project].to_i
      when 1 then
        @featureFile = File.join(File.dirname(__FILE__), "..", "..", "features", "get", "standalone.feature")
      when 2 then
        @featureFile = File.join(File.dirname(__FILE__), "..", "..", "features", "get", "online.feature")
      when 3 then
        @featureFile = File.join(File.dirname(__FILE__), "..", "..", "features", "get", "18183.feature")
      when 4 then
        @featureFile = File.join(File.dirname(__FILE__), "..", "..", "features", "get", "comepete.feature")
      when 5 then
        @featureFile = File.join(File.dirname(__FILE__), "..", "..", "features", "get", "ios.feature")
      when 6 then
        @featureFile = File.join(File.dirname(__FILE__), "..", "..", "features", "get", "mobileassistant.feature")
      when 7 then
        @featureFile = File.join(File.dirname(__FILE__), "..", "..", "features", "get", "onesdk.feature")
      when 8 then
        @featureFile = File.join(File.dirname(__FILE__), "..", "..", "features", "get", "CRM.feature")
    else
      raise "invalid project"
    end
# 在前台的view视图中直接调用iframe访问对应url
# 绝对 URL - 指向其他站点（比如 src="www.example.com/index.html"）
# 相对 URL - 指向站点内的文件（比如 src="index.html"）
# 判断commit参数是否为getData_ajax
    if params[:commit] == "getData_ajax" || params[:commit] == "获取数据"
      @get_url = @get[:url]
      @get_url = "http://#{@get[:url]}" unless @get[:url].include? "http"
      begin
        require 'myhttp'
        result = MyHttp.get(@get_url, :format =>'json')
        array = @get[:result].gsub(' ','').chomp.split("\r\n")
        @wrongmsg = ""
        allin = false
        array.each do |line|
          allin = true
          @preview_results = result.include?"#{line}"
          unless @preview_results then
            allin = false
            @wrongmsg = "#{line} 在返回结果中未匹配到"
            break
          end
        end
        if allin then
          @wrongmsg = "对比成功"
        end
        @preview_result = result
      rescue Exception => e
        @error = "Error: #{e}"
      end
      respond_to do |format|
# ajax异步调用
          format.js {}
      end
    else
# 如果commit不带参数，则转到创建成功页面或提示失败
      respond_to do |format|
        if @get.save
# 保存成功后，先创建cucumber测试用例
          Features.get_create(@featureFile, @get)
# 转到创建成功页面
          format.html { redirect_to @get, notice: 'Get was successfully created.' }
          format.json { render :show, status: :created, location: @get }
          format.js { redirect_to @get, notice: 'Get was successfully created.' }
        else
# 创建失败，提示错误信息，重新渲染新建页面，保留输入信息
          format.html { render :new }
          format.json { render json: @get.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /gets/1
  # PATCH/PUT /gets/1.json
# 对应于编辑界面
  def update
    if params[:commit] == "getData_ajax" || params[:commit] == "获取数据"
      @get = Get.new(get_params)
      @get_url = @get[:url]
      @get_url = "http://#{@get[:url]}" unless @get[:url].include? "http"
      begin
        require 'myhttp'
        result = MyHttp.get(@get_url, :format =>'json')
        array = @get[:result].gsub(' ','').chomp.split("\r\n")
        allin = false
        array.each do |line|
          @preview_results = result.include?"#{line}"
          allin = true
          unless @preview_results then
            allin = false
            @wrongmsg = "#{line} 在返回结果中未匹配到"
            break
          end
        end
        if allin then
          @wrongmsg = "对比成功"
        end
        @preview_result = result
      rescue Exception => e
        @error = "Error: #{e}"
      end

      respond_to do |format|
# ajax异步调用
          format.js {}
      end
    else
      respond_to do |format|
# 如果用例更新成功后，先删除cucumber旧的测试用例，再添加更新后的测试用例到cucumber文件中
        if @get.update(get_params)
# 删除老的cucumber测试用例
          case @get[:project].to_i
            when 1 then
              @featureFile = File.join(File.dirname(__FILE__), "..", "..", "features", "get", "standalone.feature")
            when 2 then
              @featureFile = File.join(File.dirname(__FILE__), "..", "..", "features", "get", "online.feature")
            when 3 then
              @featureFile = File.join(File.dirname(__FILE__), "..", "..", "features", "get", "18183.feature")
            when 4 then
              @featureFile = File.join(File.dirname(__FILE__), "..", "..", "features", "get", "compete.feature")
            when 5 then
              @featureFile = File.join(File.dirname(__FILE__), "..", "..", "features", "get", "ios.feature")
            when 6 then
              @featureFile = File.join(File.dirname(__FILE__), "..", "..", "features", "get", "mobileassistant.feature")
            when 7 then
              @featureFile = File.join(File.dirname(__FILE__), "..", "..", "features", "get", "onesdk.feature")
            when 8 then
              @featureFile = File.join(File.dirname(__FILE__), "..", "..", "features", "get", "CRM.feature")
          else
            raise "invalid project"
          end
          Features.destroy(@featureFile, @get)
# 添加新的cucumber测试用例
          Features.get_create(@featureFile, @get)
# 提示更新成功
          format.js {}
          format.html { redirect_to @get, notice: 'Get was successfully updated.' }
          format.json { render :show, status: :ok, location: @get }
        else
# 更新失败，提示失败原因
          format.js {}
          format.html { render :edit }
          format.json { render json: @get.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /gets/1
  # DELETE /gets/1.json
# 对应于用例删除按钮，删除用例
  def destroy
    @get.destroy
# 如果删除成功，则删除对应的cucumber测试用例
    case @get[:project].to_i
      when 1 then
        @featureFile = File.join(File.dirname(__FILE__), "..", "..", "features", "get", "standalone.feature")
      when 2 then
        @featureFile = File.join(File.dirname(__FILE__), "..", "..", "features", "get", "online.feature")
      when 3 then
        @featureFile = File.join(File.dirname(__FILE__), "..", "..", "features", "get", "18183.feature")
      when 4 then
        @featureFile = File.join(File.dirname(__FILE__), "..", "..", "features", "get", "compete.feature")
      when 5 then
        @featureFile = File.join(File.dirname(__FILE__), "..", "..", "features", "get", "ios.feature")
      when 6 then
        @featureFile = File.join(File.dirname(__FILE__), "..", "..", "features", "get", "mobileassistant.feature")
      when 7 then
        @featureFile = File.join(File.dirname(__FILE__), "..", "..", "features", "get", "onesdk.feature")
      when 8 then
        @featureFile = File.join(File.dirname(__FILE__), "..", "..", "features", "get", "CRM.feature")
    else
      raise "invalid project"
    end
    Features.destroy(@featureFile, @get)
# 提示删除成功
    respond_to do |format|
      format.html { redirect_to gets_url, notice: 'Get was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
# 查找要操作的get对象
    def set_get
      @get = Get.find(params[:id])
    end

# 设置要编辑的cucumber feature文件
    def set_featureFile
      @featureFile = File.join(File.dirname(__FILE__), "..", "..", "features", "get", "get_json.feature")
    end

    # Never trust parameters from the scary internet, only allow the white list through.
# 限制参数，只允许需要的参数操作，保证安全
    def get_params
      params.require(:get).permit(:title, :url, :result, :project)
    end
end

app/helpers/gets_helper.rb
module GetsHelper
end

app/views/gets/_form.html.erb
<%= form_for(@get, remote: true) do |f| %>
  <% if @get.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@get.errors.count, "error") %> prohibited this get from being saved:</h2>

      <ul>
      <% @get.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t(:case_title) %><br>
    标题参考格式：接口名称 tag号（针对中间层）测试点描述<br>
    如：/gamesdk/login tag=4 用户登录成功
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label t(:project) %><br>
    <%= f.select(:project, [
      ['单机SDK', 1], ['网游SDK', 2],
      ['18183', 3], ['争霸赛', 4],
      ['iOS SDK', 5], ['百度星玩家', 6],
      ['onesdk', 7], ['CRM星玩家', 8]
      ]) %>
  </div>
  <div class="field">
    <%= f.label t(:url) %><br>
    <%= f.text_area :url, class: "form-control", rows: "6" %>
  </div>
  <div class="field">
    <%= f.label t(:expected_result) %><br>
    <%= f.text_area :result, class: "form-control", rows: "8" %>
    支持多个检查点,一行一个检查点
  </div>
  <%= f.submit class: "btn btn-success" %>
  <%= link_to t(:back), gets_path, class: "btn btn-default" %>
  <%= f.submit t("getData_ajax"), class: "btn btn-primary" %>
<% end %>

app/views/gets/_form_show.html.erb
<%= form_for(@get, remote: true) do |f| %>
  <% if @get.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@get.errors.count, "error") %> prohibited this get from being saved:</h2>

      <ul>
      <% @get.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t(:case_title) %><br>
    标题参考格式：接口名称 tag号（针对中间层）测试点描述<br>
    如：/gamesdk/login tag=4 用户登录成功
    <%= f.text_field :title, class: "form-control", readonly: "true" %>
  </div>
  <div class="field">
    <%= f.label t(:project) %><br>
    <%= f.select(:project, [
      ['单机SDK', 1], ['网游SDK', 2],
      ['18183', 3], ['争霸赛', 4],
      ['iOS SDK', 5], ['百度星玩家', 6],
      ['onesdk', 7], ['CRM星玩家', 8],
      ['百度游戏',9]
      ]) %>
  </div>
  <div class="field">
    <%= f.label t(:url) %><br>
    <%= f.text_area :url, class: "form-control", rows: "6", readonly: "true" %>
  </div>
  <div class="field">
    <%= f.label t(:expected_result) %><br>
    <%= f.text_area :result, class: "form-control", rows: "8", readonly: "true" %>
    支持多个检查点,一行一个检查点
  </div>
  <%= link_to 'Edit', edit_get_path(@get),class: "btn btn-success" %>
  <%= link_to t(:back), gets_path, class: "btn btn-default" %>
  <%= f.submit t("getData_ajax"), class: "btn btn-primary" %>
<% end %>

app/views/gets/_getdata.html.erb
<div id="get_response">
  <label>
    <%= t(:expected_result) %><br />
  </label>
  <br />
  <pre lang="zh">
    <%= @wrongmsg.force_encoding("UTF-8") unless @wrongmsg.nil? %>
  </pre>
  <pre lang="zh">
    <p style="color:red">
    <% if @error %>
      <%= @error %>
    <% end %>
    </p>
    <%= JSON.pretty_generate(JSON.parse(@preview_result.force_encoding("UTF-8"))) unless @preview_result.nil? %>
  </pre>
</div>

app/views/gets/create.js.erb
if ($("#get_response"))
{
  $("#get_response").remove();
  $("<%= escape_javascript(render 'getdata' ) %>").appendTo("#getData");
}

app/views/gets/edit.html.erb
<div id="caseEdit" class="col-md-6">
  <h2><%=t :case_edit %></h2>
  <%= render 'form' %>
</div>

<div id="getData" class="col-md-6">
  <h2>测试结果</h2>
  <%= render 'preview' %>
</div>

app/views/gets/index.html.erb
<div class="col-md-1">
</div>

<div class="col-md-10">
  <h2>Get <%= t :case_list %></h2>

  <%= link_to t(:new_case), new_get_path, class: "btn btn-primary" %>
  | <%= link_to '单机SDK', gets_path(:project => 1) %>
  | <%= link_to '网游SDK', gets_path(:project => 2) %> | <%= link_to '18183', gets_path(:project => 3) %>
  | <%= link_to '争霸赛', gets_path(:project => 4) %> | <%= link_to 'iOS SDK', gets_path(:project => 5) %>
  | <%= link_to '百度星玩家', gets_path(:project => 6) %> | <%= link_to 'onesdk', gets_path(:project => 7) %>
  | <%= link_to 'CRM星玩家', gets_path(:project => 8) %> | <br/><br/>


  <table class="table">
    <tr>
      <th><%= t :case_title %></th>
      <th colspan="3"></th>
    </tr>



    <% @gets.each do |get| %>
        <tr>
          <td><b><%= link_to get.title, get_path(get) %></b></td>
          <td class="text-right"><%= link_to t(:show), get %></td>
          <td class="text-center"><%= link_to t(:edit), edit_get_path(get) %></td>
          <td><%= link_to t(:destroy), get, method: :delete, data: {confirm: t(:are_you_sure)} %></td>
        </tr>
    <% end %>

  </table>
  <div style="text-align: center">
    <%= will_paginate @gets, :container => false %>
  </div>

</div>

<div class="col-md-1">
</div>

app/views/gets/new.html.erb
<div id="caseRecord" class="col-md-6">
  <h2><%=t :add_case %></h2>
  <%= render 'form' %>
</div>

<div id="getData" class="col-md-6">
  <h2><%=t :get_data %></h2>
  <%= render 'preview' %>
</div>

app/views/gets/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Showing get</h1>

<div id="caseRecord" class="col-md-6">
  <h2>测试用例</h2>
  <%= render 'form_show' %>
</div>

<div id="getData" class="col-md-6">
    <h2><%=t :get_data %></h2>
    <%= render 'preview' %>
</div>

app/views/gets/update.js.erb
<% if params[:commit] == "getData_ajax" || params[:commit] == "获取数据" %>
  if ($("#get_response"))
  {
    $("#get_response").remove();
    $("#get_p").remove();
    $("<%= escape_javascript(render 'getdata' ) %>").appendTo("#getData");
  }
<% else %>
  if ($("#get_response"))
  {
    $("#get_response").remove();
    $("#get_p").remove();
    $("<p id='get_p'>更新Successful!</p>").appendTo("#getData");
  }
<% end %>