config/routes.rb
Rails.application.routes.draw do

  get 'tools/index'

  resources :information

  root 'welcome#index'
  get 'welcome/index'

  resources :gets

  get 'posts/test'
  resources :posts

end

app/models/information.rb
class Information < ActiveRecord::Base
end

app/controllers/information_controller.rb
class InformationController < ApplicationController
  before_action :set_information, only: [:show, :edit, :update, :destroy]

  # GET /information
  # GET /information.json
  def index
    @information = Information.all
  end

  # GET /information/1
  # GET /information/1.json
  def show
  end

  # GET /information/new
  def new
    @information = Information.new
  end

  # GET /information/1/edit
  def edit
  end

  # POST /information
  # POST /information.json
  def create
    @information = Information.new(information_params)

    respond_to do |format|
      if @information.save
        format.html { redirect_to @information, notice: 'Information was successfully created.' }
        format.json { render :show, status: :created, location: @information }
      else
        format.html { render :new }
        format.json { render json: @information.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /information/1
  # PATCH/PUT /information/1.json
  def update
    respond_to do |format|
      if @information.update(information_params)
        format.html { redirect_to @information, notice: 'Information was successfully updated.' }
        format.json { render :show, status: :ok, location: @information }
      else
        format.html { render :edit }
        format.json { render json: @information.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /information/1
  # DELETE /information/1.json
  def destroy
    @information.destroy
    respond_to do |format|
      format.html { redirect_to information_index_url, notice: 'Information was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_information
      @information = Information.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def information_params
      params.require(:information).permit(:title, :description)
    end
end

app/helpers/information_helper.rb
module InformationHelper
end

app/views/information/_form.html.erb
<%= form_for(@information) do |f| %>
  <% if @information.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@information.errors.count, "error") %> prohibited this information from being saved:</h2>

      <ul>
      <% @information.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-md-1">
      <%= f.label :title, class: "btn btn-default" %>
    </div>
    <div class="col-md-9">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <p>
    <%= f.text_area :description, class: "form-control", rows: 30, style: "width: 100%" %>
  </p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/information/edit.html.erb
<h1>Editing information</h1>

<%= render 'form' %>

<%= link_to 'Show', @information %> |
<%= link_to 'Back', information_index_path %>

app/views/information/index.html.erb
<div class="col-md-1">
</div>
<div class="col-md-10">
<h2>Listing information</h2>

<table class="table">
  <tr>
    <th>Title</th>
    <th colspan="3"></th>
  </tr>

  <% @information.each do |information| %>
    <tr>
      <td><%= link_to information.title, information_path(information) %></td>
      <td><%= link_to 'Show', information %></td>
      <td><%= link_to 'Edit', edit_information_path(information) %></td>
      <td><%= link_to 'Destroy', information, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<br>

<%= link_to 'New Information', new_information_path %>
</div>

<div class="col-md-1">
</div>

app/views/information/new.html.erb
<div class="col-md-1">
</div>
j
<div class="col-md-10">
<h1>New information</h1>

<%= render 'form' %>

<%= link_to 'Back', information_index_path %>
</div>

<div class="col-md-1">
</div>

app/views/information/show.html.erb
<div class="col-md-1">
</div>

<div class="col-md-10">
  <p id="notice"><%= notice %></p>
  
  <!-- title -->
  <h2 class="blog-post-title text-center">
    <%= @information.title %>
  </h2>
  <p class="text-center">
  <%= @information.created_at.strftime("%B %e %k:%M - %Y") %>
  </p>
  
  <%= markdown( @information.description ) %>
  
  <br />
  <%= link_to 'Edit', edit_information_path(@information) %> |
  <%= link_to 'Back', information_index_path %>
</div>

<div class="col-md-1">
</div>