config/routes.rb
Rails.application.routes.draw do

  get 'tools/index'

  resources :information

  root 'welcome#index'
  get 'welcome/index'

  resources :gets

  get 'posts/test'
  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
# posts数据库表有5个字段，都是必须有的
  validates :title, presence: true
# 这个字段已经变成下拉列表，所以一定会有值，不需要验证
#validates :project, presence: true
  validates :url, presence: true
# parameter暂时不设置为必选项
#  validates :parameter, presence: true
  validates :data, presence: true
  validates :result, presence: true
end

app/controllers/posts_controller.rb
require 'pry'
class PostsController < ApplicationController
  # 在执行方法之前先
  # 1. 查找到对应的get数据
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  # 2. 设置好cucumber自动化测试文件的路径
  before_action :set_featureFile, only: [:create, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  # 对应于前台的"post用例列表"
  def index
    if params[:project].nil?
      @posts = Post.all
      @posts = Post.paginate :page => params[:page],
                           :per_page => 10
    else
      @posts = Post.where(project: "#{params[:project].to_i}").order("title").paginate :page => params[:page],
                                                                                       :per_page => 10
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/test
  # 对应于前台的"Post测试"，执行接口测试
  def test
    @post = Post.new
  end

  # GET /posts/new
  # 对应于前台的"新建Post用例"，创建用例页面，输入参数页面
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  # 点击"新建Post用例页面"的创建按钮，后台执行的操作，保存测试用例，同时创建cucumber自动化测试用例
  def create
    data = @post[:data]
    # 处理url前面不带http的url，加上http://
    if @post[:url].include? "http"
      url = @post[:url]
    else
      url = "http://#{@post[:url]}"
    end

    case @post[:project].to_i
      when 1, 2, 3, 4 then
        key = ENV['KEY1']
      when 5, 6, 9  then
        key = ENV['KEY2']
      when 8 then
        key = ENV['KEY3']
      else
        key = 'none'
    end
    # 对post data数据加密后发送给后台server，获取后台server的返回结果，返回给前台展示
    # 判断commit参数是否为getData_ajax，利用ajax技术局部更新
    if params[:commit] == "Get Data" || params[:commit] == "获取数据"
      # require 加密类
      require 'AES'
      # 此处实现AES/ECB/pkcs5padding加密，Base64编码
      # 利用httparty的post类方法发送加密的data到server
      # 此处的self.class.get调用的是include HTTParty类中的方法post
      if key == "none"

        begin
          @preview = AES.get_json_by_post_without_encode(url, data)
        rescue Exception => e
          @error = "Error: #{e} \n #{Rails.backtrace_cleaner.clean(e.backtrace).join("\n")}"
        end

      else

        begin
          # preview_result只是临时变量，存储测试返回的数据，不入库
          @preview = AES.get_json_by_post(url, key, data)
        rescue Exception => e
          @error = "Error: 项目选择是否正确？\n #{e} \n #{Rails.backtrace_cleaner.clean(e.backtrace).join("\n")}"
        end

      end

      begin
        array = @post[:result].gsub(' ','').chomp.split("\r\n")
        @wrongmsg = ""
        allin = false
        array.each do |line|
          allin = true
          @preview_results = @preview.force_encoding("UTF-8").include?"#{line}"
          unless @preview_results then
            allin = false
            @wrongmsg = "#{line} 在返回结果中未匹配到"
            break
          end
        end
        if allin then
          @wrongmsg = "对比成功"
        end
        @preview_result = @preview
      rescue Exception => e
        @error = "Error: #{e}"
      end
      respond_to do |format|
        format.js {}
      end
    else
      # 正常commit，保存输入参数到数据库
      respond_to do |format|
        if @post.save
          # 保存成功后，先创建cucumber测试用例
          # Features.post_create(@featureFile, @post)
          # 转到创建成功页面
          format.html { redirect_to @post, notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
          format.js { render :layout => false }
        else
          # 创建失败，提示错误信息，重新渲染新建页面，保留输入信息
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
          format.js { render :layout => false, :status => 406 }
        end
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  # 对应于编辑界面
  def update
    if params[:commit] == "Get Data" || params[:commit] == "获取数据"
      @post = Post.new(post_params)
    end
    data = @post[:data]
    # 处理url前面不带http的url，加上http://
    if @post[:url].include? "http"
      url = @post[:url]
    else
      url = "http://#{@post[:url]}"
    end

    case @post[:project].to_i
      when 1, 2, 3, 4 then
        key = ENV['KEY1']
      when 5, 6, 9  then
        key = ENV['KEY2']
      when 8 then
        key = ENV['KEY3']
      else
        key = 'none'
    end
    # 对post data数据加密后发送给后台server，获取后台server的返回结果，返回给前台展示
    # 判断commit参数是否为getData_ajax，利用ajax技术局部更新
    if params[:commit] == "Get Data" || params[:commit] == "获取数据"
      # require 加密类
      require 'AES'
      # 此处实现AES/ECB/pkcs5padding加密，Base64编码
      # 利用httparty的post类方法发送加密的data到server
      # 此处的self.class.get调用的是include HTTParty类中的方法post
      if key == "none"
        begin
          @preview = AES.get_json_by_post_without_encode(url, data)
        rescue Exception => e
          @error = "Error: #{e} \n #{Rails.backtrace_cleaner.clean(e.backtrace).join("\n")}"
        end
      else
        begin
          # preview_result只是临时变量，存储测试返回的数据，不入库
          @preview = AES.get_json_by_post(url, key, data)
        rescue Exception => e
          @error = "Error: #{e} \n #{Rails.backtrace_cleaner.clean(e.backtrace).join("\n")}"
        end
      end

      # 如果请求发送错误后，不需要进行下面的操作
      if ! @preview.nil?
        begin
          array = @post[:result].gsub(' ','').chomp.split("\r\n")
          @wrongmsg = ""
          allin = false
          array.each do |line|
            allin = true
            @preview_results = @preview.force_encoding("UTF-8").include?"#{line}"
            unless @preview_results then
              allin = false
              @wrongmsg = "#{line} 在返回结果中未匹配到"
              break
            end
          end
          if allin then
            @wrongmsg = "对比成功"
          end
          @preview_result = @preview
        rescue Exception => e
          @error = "Error: #{e}"
        end
      end
      respond_to do |format|
        format.js {}
      end
    else
      respond_to do |format|
        # 如果用例更新成功后，先删除cucumber旧的测试用例，再添加更新后的测试用例到cucumber文件中
        if @post.update(post_params)
          # 删除老的cucumber测试用例
          # Features.destroy(@featureFile, @post)
          # 添加新的cucumber测试用例
          # Features.post_create(@featureFile, @post)
          # 提示更新成功
          format.html { redirect_to @post, notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
          format.js { render :layout => false }
        else
          # 更新失败，提示失败原因
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
          format.js { render :layout => false, :status => 406 }
        end
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  # 对应于用例删除按钮，删除用例
  def destroy
    @post.destroy
    # 如果删除成功，则删除对应的cucumber测试用
    # Features.destroy(@featureFile, @post)
    # 提示删除成功
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # 查找要操作的post对象
    def set_post
      @post = Post.find(params[:id])
    end

    # 设置要编辑的cucumber feature文件
    def set_featureFile
      if @post.nil?
        # 获取页面填写的post参数
        @post = Post.new(post_params)
      end
      case @post[:project].to_i
        when 1 then
          @featureFile = File.join(File.dirname(__FILE__), "..", "..", "features", "post", "standalone.feature")
        when 2 then
          @featureFile = File.join(File.dirname(__FILE__), "..", "..", "features", "post", "online.feature")
        when 3 then
          @featureFile = File.join(File.dirname(__FILE__), "..", "..", "features", "post", "18183.feature")
        when 4 then
          @featureFile = File.join(File.dirname(__FILE__), "..", "..", "features", "post", "compete.feature")
        when 5 then
          @featureFile = File.join(File.dirname(__FILE__), "..", "..", "features", "post", "ios.feature")
        when 6 then
          @featureFile = File.join(File.dirname(__FILE__), "..", "..", "features", "post", "mobileassistant.feature")
        when 7 then
          @featureFile = File.join(File.dirname(__FILE__), "..", "..", "features", "post", "onesdk.feature")
        when 8 then
          @featureFile = File.join(File.dirname(__FILE__), "..", "..", "features", "post", "CRM.feature")
        when 9 then
          @featureFile = File.join(File.dirname(__FILE__), "..", "..", "features", "post", "baidu_game.feature")
        else
          puts "new project here, not build feature file"
          #raise "invalid project"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # 限制参数，只允许需要的参数操作，保证安全
    def post_params
      params_tmp = params.require(:post).permit(:title, :url, :parameter, :data, :result)
      params_tmp[:project] = params[:project]
      params_tmp
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post, remote: true) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this get from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t(:case_title) %><br>
    <%= f.text_field :title, class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label t(:project) %><br>
    <%= select_tag(:project, options_for_select([
          ['单机SDK', 1], ['网游SDK', 2],
          ['18183', 3], ['争霸赛', 4],
          ['IOS SDK', 5], ['百度星玩家', 6],
          ['oneSDK', 7], ['CRM星玩家', 8]
          ], @post[:project])) %>
  </div>
  <div>
    <%= f.label t(:url) %><br />
    <%= f.text_field :url, class: "form-control" %>
  </div>
  <div>
    <%= f.label t(:data) %><br />
    <%= f.text_area :data, class: "form-control", rows: "3" %>
  </div>
  <div>
    <%= f.label t(:expected_result) %><br />
    <%= f.text_area :result, class: "form-control", rows: "8"%>
    支持多个检查点,一行一个检查点
  </div>
  <br />
  <%= f.submit class: "btn btn-success" %>
  <%= link_to t(:back), posts_path, class: "btn btn-default" %>
  <%= f.submit t("getData_ajax"), class: "btn btn-primary" %>
<% end %>

app/views/posts/_form_auto.html.erb
<%= form_for(@post, remote: true) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this get from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t(:case_title) %><br>
    标题参考格式：接口名称 tag号（针对中间层）测试点描述<br>
    如：/gamesdk/login tag=4 用户登录成功
    <%= f.text_field :title, class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label t(:project) %><br>
    <%= select_tag(:project, options_for_select([
          ['单机SDK', 1], ['网游SDK', 2],
          ['18183', 3], ['争霸赛', 4],
          ['IOS SDK', 5], ['百度星玩家', 6],
          ['不加密', 7], ['CRM星玩家', 8],
          ['百度游戏', 9],['CPS', 10]
          ], @post[:project]), class: "form-control") %>
  </div>
  <div>
    <%= f.label t(:url) %><br />
    <%= f.text_area :url, class: "form-control", rows: "3" %>
  </div>
  <div>
    <%= f.label "参数" %> | 请输入上方网址端口号后的参数<br />
    http://[URL]:[PORT]/<%= f.text_field :parameter, class: "form-control" %>
  </div>
  <div>
    <%= f.label t(:data) %><br />
    <%= f.text_area :data, class: "form-control", rows: "8" %>
  </div>
  <div>
    <%= f.label t(:expected_result) %><br />
    <%= f.text_area :result, class: "form-control", rows: "8"%>
    支持多个检查点,一行一个检查点
  </div>
  <br />
  <%= f.submit class: "btn btn-success" %>
  <%= link_to t(:back), posts_path, class: "btn btn-default" %>
  <%= f.submit t("getData_ajax"), class: "btn btn-primary" %>
<% end %>

app/views/posts/_form_show.html.erb
<%= form_for(@post, remote: true) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this get from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t(:case_title) %><br>
    标题参考格式：接口名称 tag号（针对中间层）测试点描述<br>
    如：/gamesdk/login tag=4 用户登录成功
    <%= f.text_field :title, class: "form-control", readonly: "true" %>
  </div>
  <div class="field">
    <%= f.label t(:project) %><br>
    <%= select_tag(:project, options_for_select([
          ['单机SDK', 1], ['网游SDK', 2],
          ['18183', 3], ['争霸赛', 4],
          ['IOS SDK', 5], ['百度星玩家', 6],
          ['不加密', 7], ['CRM星玩家', 8],
          ['百度游戏', 9], ['CPS', 10]
          ], @post[:project]), class: "form-control") %>
  </div>
  <div>
    <%= f.label t(:url) %><br />
    <%= f.text_area :url, class: "form-control", rows: "3", readonly: "true" %>
  </div>
  <div>
    <%= f.label "参数" %> | 请输入上方网址端口号后的参数<br />
    http://[URL]:[PORT]/<%= f.text_field :parameter, class: "form-control", readonly: "true" %>
  </div>
  <div>
    <%= f.label t(:data) %><br />
    <%= f.text_area :data, class: "form-control", rows: "8", readonly: "true" %>
  </div>
  <div>
    <%= f.label t(:expected_result) %><br />
    <%= f.text_area :result, class: "form-control", rows: "8", readonly: "true" %>
    支持多个检查点,一行一个检查点
  </div>
  <br />
  <%= link_to 'Edit', edit_post_path(@post),class: "btn btn-success" %>
  <%= link_to t(:back), posts_path, class: "btn btn-default" %>
  <%= f.submit t("getData_ajax"), class: "btn btn-primary" %>
<% end %>

app/views/posts/_form_test.html.erb
<%= form_for(@post, remote: true) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this get from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t(:case_title) %><br>
    <%= f.text_field :title, class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label t(:project) %><br>
    <%= select_tag(:project, options_for_select([
          ['单机SDK', 1], ['网游SDK', 2],
          ['18183', 3], ['争霸赛', 4],
          ['IOS SDK', 5], ['百度星玩家', 6],
          ['不加密', 7], ['CRM星玩家', 8],
          ['百度游戏', 9], ['CPS', 10]
          ], @post[:project]), class: "form-control") %>
  </div>
  <div>
    <%= f.label t(:url) %><br />
    <%= f.text_field :url, class: "form-control" %>
  </div>
  <div>
    <%= f.label t(:data) %><br />
    <%= f.text_area :data, class: "form-control", rows: "8" %>
  </div>
  <div>
    <%= f.label t(:expected_result) %><br />
    <%= f.text_area :result, class: "form-control", rows: "8"%>
    支持多个检查点,一行一个检查点
  </div>
  <br />
  <%= f.submit t("getData_ajax"), class: "btn btn-primary" %>
  <%= link_to t(:back), posts_path, class: "btn btn-default" %>
<% end %>

app/views/posts/_getdata.html.erb
<div id="get_response">
  <label>
    <%= t(:expected_result) %><br />
  </label>
  <br />
  <pre lang="zh">
    <%= @wrongmsg.force_encoding("UTF-8") unless @wrongmsg.nil? %>
  </pre>
  <pre lang="zh">
    <p style = "color:red">
    <% if @error %>
      <%= @error%>
    <% end %>
    </p>
  <%if !@preview_result.nil? %>
    <% if @preview_result.class == String %>
      <%= JSON.parse(@preview_result.force_encoding("UTF-8")) %>
    <% else %>
      <%= JSON.pretty_generate(JSON.parse(@preview_result.force_encoding("UTF-8"))) unless @preview_result.nil? %>
    <% end %>
  <% end %>
  </pre>
</div>

app/views/posts/_preview.html.erb
<%= render 'getdata' %>

app/views/posts/create.js.erb
if ($("#get_response"))
{
  <% if params[:commit] == "获取数据" %>
    $("#getData div").remove();
  <% end %>
  $("<%= escape_javascript(render 'getdata') %>").appendTo("#getData");
}
<% if @post.errors.empty? %>
  alert("Successful!");
<% else %>
  $('#caseRecord').prepend($('<div class="error-message bg-danger"><%= escape_javascript(@post.errors.full_messages.join("  |  ")) %></pre></div>'));
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<div class="col-md-1">
</div>
<div class="col-md-10">
  <h2>Post <%= t :case_list %></h2>

  <%= link_to t(:new_case), new_post_path, class: "btn btn-primary right" %>

  <ul class="nav nav-tabs">
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        项目 <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to 'CPS', posts_path(:project => 10) %></li>
        <li><%= link_to '单机SDK', posts_path(:project => 1) %></li>
        <li><%= link_to '网游SDK', posts_path(:project => 2) %></li>
        <li><%= link_to '18183', posts_path(:project => 3) %></li>
        <li><%= link_to '争霸赛', posts_path(:project => 4) %></li>
        <li class="divider"></li>
        <li><%= link_to 'iOS SDK', posts_path(:project => 5) %></li>
      </ul>
    </li>
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        版本 <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to 'CPS', posts_path(:project => 10) %></li>
        <li><%= link_to '单机SDK', posts_path(:project => 1) %></li>
        <li><%= link_to '网游SDK', posts_path(:project => 2) %></li>
        <li><%= link_to '18183', posts_path(:project => 3) %></li>
        <li><%= link_to '争霸赛', posts_path(:project => 4) %></li>
        <li class="divider"></li>
        <li><%= link_to 'iOS SDK', posts_path(:project => 5) %></li>
      </ul>
    </li>
  </ul>

  <br/><br/>

  <table class="table">
    <tr>
      <th><%= t :case_title %></th>
      <th colspan="3"></th>
    </tr>

    <% @posts.each do |post| %>
        <tr>
          <td><b><%= link_to post.title, post_path(post) %></b></td>
          <td class="text-right"><%= link_to t(:show), post %></td>
          <td class="text-center"><%= link_to t(:edit), edit_post_path(post) %></td>
          <td><%= link_to t(:destroy), post, method: :delete, data: {confirm: t(:are_you_sure)} %></td>
        </tr>
    <% end %>
  </table>
  <div style="text-align: center">
    <%= will_paginate @gets, :container => false %>
  </div>

</div>

<div class="col-md-1">
</div>

app/views/posts/new.html.erb
<div id="caseRecord" class="col-md-6">
  <h2><%=t :add_case %></h2>
  <%= render 'form_auto' %>
</div>

<div id="getData" class="col-md-6">
  <h2><%=t :get_data %></h2>
  <%= render 'preview' %>
</div>

app/views/posts/show.html.erb
<h1>Showing post</h1>

<div id="caseRecord" class="col-md-6">
  <h2>测试用例</h2>
  <%= render 'form_show' %>
</div>

<div id="getData" class="col-md-6">
  <h2><%=t :get_data %></h2>
  <%= render 'preview' %>
</div>

app/views/posts/test.html.erb
<div id="caseRecord" class="col-md-6">
  <h2><%= "执行测试" %></h2>
  <%= render 'form_test' %>
</div>

<div id="getData" class="col-md-6">
  <h2><%= t(:get_data) %></h2>
  <%= render 'preview' %>
</div>

app/views/posts/update.js.erb
if ($("#get_response"))
{
  <% if params[:commit] == "获取数据" %>
    $("#getData div").remove();
  <% end %>
  $("<%= escape_javascript(render 'getdata') %>").appendTo("#getData");
}
<% if @post.errors.empty? %>
  alert("Successful!");
<% else %>
  $('#caseRecord').prepend($('<div class="error-message bg-danger"><%= escape_javascript(@post.errors.full_messages.join("  |  ")) %></pre></div>'));
<% end %>