config/routes.rb
Rails.application.routes.draw do

  get 'tools/index'

  resources :information

  root 'welcome#index'
  get 'welcome/index'

  resources :gets

  get 'posts/test'
  resources :posts

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>apiTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script type="text/javascript">
    var ready;
    ready = function() {
      var str = window.location.href;
      var url = str.replace(/^(?:\/\/|[^\/]+)*/, "");
      $('.nav a[href="'+url+'"]').parent().addClass('active');
    };
    $(document).ready(ready);
    $(document).on('page:load', ready);
  </script>
  </head>
</head>
<body>

<!-- navigate bar 导航 -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!-- 网站 logo -->
        <a class="navbar-brand" style="color: white;" href="/">apiTest | 主页</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">

          <li class="dropdown">
            <a class="dropdown-toggle" aria-expanded="true" aria-haspopup="true" role="button" data-toggle="dropdown" href="#">
              | 用例列表 |
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Get用例列表', gets_path %></li>
              <li><%= link_to 'Post用例列表', posts_path %></li>
              <li><%= link_to '新建Get用例', new_get_path %></li>
              <li><%= link_to '新建Post用例', new_post_path %></li>
            </ul>
          </li>

          <li class="dropdown">
            <a class="dropdown-toggle" aria-expanded="true" aria-haspopup="true" role="button" data-toggle="dropdown" href="#">
              | 接口测试 |
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Get测试', new_get_path %></li>
              <li><%= link_to 'Post测试', posts_test_path %></li>
              <li><%= link_to 'rpc后端测试', 'http://10.10.0.50/rpc/' %></li>
            </ul>
          </li>

          <li><%= link_to '| 测试组信息 |', information_index_path %></li>
          <li><%= link_to '| 测试工具 |', tools_index_path %></li>
        </ul>

      </div><!--/.navbar-collapse -->
    </div><!-- /.container -->
  </nav>

  <div class="container">

    <!-- content 正文 -->
    <div class="row">
      <%= yield %>
    </div>

    <hr />
    
    <!-- footer -->
    <footer class="text-center">
      <p class="btn btn-default"> <%= link_to "apiTest v1.0.0", "/" %> </p>
    </footer>

  </div> <!-- /container -->

</body>
</html>